/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DelayedReviewStage: typeof import('./src/components/vocabulary-learning/DelayedReviewStage.vue')['default']
    LessonReader: typeof import('./src/components/vocabulary-learning/LessonReader.vue')['default']
    ProductionStage: typeof import('./src/components/vocabulary-learning/ProductionStage.vue')['default']
    ProgressBackup: typeof import('./src/components/vocabulary-learning/ProgressBackup.vue')['default']
    RecallStage: typeof import('./src/components/vocabulary-learning/RecallStage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TopicDashboard: typeof import('./src/components/vocabulary-learning/TopicDashboard.vue')['default']
    WordCardPanel: typeof import('./src/components/vocabulary-learning/WordCardPanel.vue')['default']
  }
}
